ボウリングのスコア計算プログラムオブジェクト指向版の提出物です。
fjordllc/ruby-practices pull request #17
Opened 2020-12-04 07:08 UTC by tam-03

- ボウリングのスコア計算プログラムをオブジェクト指向で書く。
- スコアには「旧ルール」を使用する

## スクリーンショット
[![Image from Gyazo](https://i.gyazo.com/f842608a8a5e838a5910c700235dc61b.jpg)](https://gyazo.com/f842608a8a5e838a5910c700235dc61b)

ご確認をよろしくお願い致します🙇🏻‍♂️

2020-12-08 03:44 UTC, u1tnk requested changes
まず、Object指向でコードが増える事はありますが、読みやすく、理解しやすくする為のものなので、現状は https://gist.github.com/tam-03/dbd888e3e98991fda94f7f71aa9a7f7b の方が読みやすいので良くないです。

大きめで申し訳無いのですが、クラス構成から考えなおした方が良いと思います。

- 別途コメントしてますが、単機能のクラスが多いです。この規模なら Game/Frame/Shotぐらいの構成で良さそうなので、まとめる事を考えてみてください。
- attr_readerは インスタンス変数に必須では無いです。どちらかというと無い方がカプセル化が守られて良いです。できればinitializeで必要な情報を与えて、メソッドで必要な情報のみ返してもらうようにしましょう。

全体的な細かい指摘

- .gitkeepの削除がコミットされてます。この課題以外のディレクトリを削除した結果だと思いますが、diffに表示されてしまいますし、何もしなくて良かったです。

2020-12-08 03:44 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +    @first_frame = Frame.new(frame[0])
Gameに @frames にして配列で持たせた方が良いと思います。

2020-12-08 03:44 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +  def frames_array_convert
この機能はGameクラスに持ってて良いと思います。

2020-12-08 03:44 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +class StrikeConvert
一つの機能をクラスとして切り出すのはクラスが肥大化して読みづらいときに有効なテクニックではありますが、この時点では使わなくて良いと思います。

2020-12-09 05:53 UTC, tam-03 commented
> 単機能のクラスが多いです。

> クラス構成から考えなおした方が良いと思います。

> initializeで必要な情報を与えて、メソッドで必要な情報のみ返してもらうようにしましょう。

おっしゃる通り、かなり分かり辛かったので、クラス構成を見直し、Game/Frame/Shotのみにしました！

> .gitkeepの削除がコミットされてます。

失礼しました！🙇🏻‍♂️

2020-12-09 08:45 UTC, u1tnk requested changes
前よりだいぶスッキリしましたね 👍 
ですが、もうちょっとオブジェクト指向っぽくしたいところです。

- Gameは一つで良いですが、Shot/Frameはそれぞれの一個をオブジェクトにしたい。
    - Shot/Frame全体を扱う機能(インプットからShot配列を作るとか)はクラスメソッドかGameクラスの役割で良いと思います。
- ShotやFrame自身が分かる情報はメソッド(メッセージ)で聞いてあげましょう。StrikeかSpareか10フレーム目なのか？とかですね。Game/Frame/Shotそれぞれが必要な事だけを知っていて、知らないものは他のオブジェクトに聞く事で情報と処理のセットに分けていきましょう。

2020-12-11 03:13 UTC, tam-03 commented
> Gameは一つで良いですが、Shot/Frameはそれぞれの一個をオブジェクトにしたい。

Gameクラスでスコアと加算分の計算をして、Shot/Frameを1つのオブジェクトにしました！

> Shot/Frame全体を扱う機能(インプットからShot配列を作るとか)はクラスメソッドかGameクラスの役割で良いと思います。

全体を扱う機能は、クラスメソッドにしました！

再度、ご確認をよろしくお願い致します！🙇🏻‍♂️

2020-12-12 14:34 UTC, u1tnk requested changes

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +    @frame_array = [
10行同じ事を書くのはNGです。ループでなんとかするようにしましょう。
また、 framesと複数形を使うときは frameの配列というのは慣習になっていますので、framesという名前でFrameクラスがある時点でFrameクラスのインスタンスの配列である事を期待してしまうので、合わせるようにしましょう。

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +  def self.shot_array_convert(marks)
今の名前でもダメでは無いですが、この内容だと `marks_to_shots`の方が明確で良いかなと思いました。

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +        next_frame = @frame_array[idx]
細かいですが、 idx は引数なので加算するのはあんまり良くないです。 ` @frame_array[idx + 1] `のように参照だけの方が良いと思います。

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +  def strike?
いいですね。オブジェクト指向感あります 👍

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +  def score
この名前ですが Frameのscoreという名前は曖昧に見えます。
strikeやspareを考慮したものかもしれませんし、もしかしたらこのframeまでの累計scoreかもしれません。
なので適切な名前を検討してください。

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +    return true if [@first_mark.score, @second_mark.score].sum == 10
最後の評価値が返されるので、 `return true` は不要です。
`[@first_mark.score, @second_mark.score].sum == 10` だけで大丈夫です。

また、この内容だとstrikeのときもtrueになりませんか？

2020-12-12 14:34 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +  def initialize(frame)
framesでは無くて、frameで配列になっているのも違和感がありますし、ここに渡されるのはshotsが適切だと思います。
また、 first_markにShotインスタンスが入ってるのもおかしいです。
また、first/second/third_mark は配列で対応可能なので @shotsになると良いと思います。

2020-12-14 07:25 UTC, tam-03 commented on 07.bowling_object/bowling_object.rb
> +    @frame_array = [
ループを`(0..9)`の範囲にしてindexで指定して`Frame.new`する様に変更しました。

変数名で、複数系の時は、shotかframeオブジェクトの入った配列になっている様に変更しました。

2020-12-14 07:25 UTC, tam-03 commented on 07.bowling_object/bowling_object.rb
> +        next_frame = @frame_array[idx]
参照だけの書き方があるんですね！
知りませんでした！修正しました！🙇🏻‍♂️

2020-12-14 07:25 UTC, tam-03 commented on 07.bowling_object/bowling_object.rb
> +  def score
確かに勘違いが起きそうでした。。
こちらは`shots_score`に変更したのですが、いかがでしょうか？

2020-12-14 07:25 UTC, tam-03 commented on 07.bowling_object/bowling_object.rb
> +    return true if [@first_mark.score, @second_mark.score].sum == 10
おっしゃる通りでした。。
最後の評価値が返されるのを考えて、修正しました！

2020-12-14 07:25 UTC, tam-03 commented on 07.bowling_object/bowling_object.rb
> +  def initialize(frame)
Shotクラスのクラスメソッドで`shot.new`して、Frameクラスのクラスメソッドで処理をする時にはshotオブジェクトの配列になる様に変更し、メソッドも少し変更しました！

変数名もおかしかったです🙇🏻‍♂️

2020-12-14 11:57 UTC, u1tnk requested changes

2020-12-14 11:57 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +    @mark == 'X' ? 10 : @mark.to_i
元データをそのまま保持しておいて取得するときに判断するのはオブジェクト指向っぽいですね 👍

2020-12-14 11:57 UTC, u1tnk commented on 07.bowling_object/bowling_object.rb
> +    (0..9).each do |num|
細かいえすが、 eachをmapにすれば @framesの宣言は不要ですね。
あと、 呼び出し元で @framesに入れているので、ここではインスタンス変数を使わずにreturnするだけで良いと思います。

2020-12-15 01:05 UTC, tam-03 commented on 07.bowling_object/bowling_object.rb
> +    (0..9).each do |num|
mapにして、Frame.newを返す様にしました！
eachとmapの扱い、結構曖昧に理解していました。。ありがとうございます！🙇🏻‍♂️

2021-05-13 00:20 UTC, closed without merging