#lscommand
fjordllc/ruby-practices pull request #5
Opened 2020-11-23 08:09 UTC by SeijiNumata

lsコマンドです。新要件でお願いします。

rubocop 
![image](https://user-images.githubusercontent.com/50447071/99939845-5a735780-2dae-11eb-8c6f-c011343964a4.png)

オプションなし
![image](https://user-images.githubusercontent.com/50447071/99939402-5135bb00-2dad-11eb-92ab-b2fe26649977.png)
aオプション
![image](https://user-images.githubusercontent.com/50447071/99939481-7d513c00-2dad-11eb-9d30-c709859370f0.png)
rオプション
![image](https://user-images.githubusercontent.com/50447071/99939515-8e9a4880-2dad-11eb-82ce-95d55e966bdd.png)
lオプション
![image](https://user-images.githubusercontent.com/50447071/99939534-9fe35500-2dad-11eb-9d6b-074f7f9a059a.png)
全オプション
![image](https://user-images.githubusercontent.com/50447071/99939937-8b538c80-2dae-11eb-9882-acf122600484.png)

ご確認よろしくお願いいたします！！🙇‍♂️

2020-11-23 11:23 UTC, komagata requested changes

2020-11-23 11:23 UTC, komagata commented on 05.ls/lscommand.rb
> +if options['a'] == true
rubyの式は必ずtrueかfalseに評価できるのでifなどの条件分にtrueなどと比較する文がくることはありません。

```ruby
if options['a']
```

で大丈夫です。

2020-11-23 13:24 UTC, SeijiNumata commented on 05.ls/lscommand.rb
> +if options['a'] == true
本当ですね！
修正いたしました！
ご指摘ありがとうございます。🙇‍♂️

2020-11-24 02:52 UTC, komagata requested changes

2020-11-24 02:52 UTC, komagata commented on 06.wc/wccommand.rb
> +  end
```suggestion
  else
    stdin_calc
  end
```

2020-11-24 12:28 UTC, SeijiNumata commented on 06.wc/wccommand.rb
> +  end
ありがとうございます。
修正いたしました。

2020-11-25 06:38 UTC, komagata commented
<img width="486" alt="スクリーンショット 2020-11-25 15 35 55" src="https://user-images.githubusercontent.com/16577/100191711-f7133200-2f33-11eb-85a3-b10716f6b70a.png">

commitのauthorのアイコンがおかしいようです

[コミットしたユーザーアイコンがOctcatになっていないか - 初心者がRailsプロジェクトへの初PRする前に見るチェックリスト \- komagataのブログ](https://docs.komagata.org/5676#default_icon)

2020-11-25 09:31 UTC, SeijiNumata commented
![image](https://user-images.githubusercontent.com/50447071/100208686-57ae6900-2f4c-11eb-969b-2f2ce528e6dd.png)

こちらメールの設定を見直し、pushしてアイコンが適用されていることを確認いたしました🙇‍♂️
何度もすみません。よろしくお願いいたします。

2020-11-27 06:21 UTC, komagata commented
過去のコミットも修正お願いします。これは実際の仕事でもよくあるかんじです。

2020-11-27 13:22 UTC, SeijiNumata commented
すみません、色々と試していたところ、ローカルの環境でやらかしてしまいました。
具体的には、過去のコミットも自分のプロフィール画像が反映されるようにしようとしたところ、やり方がよく分からずに試行錯誤しているうちにgitの歴史を完全に書き換えてしまい、現在ローカルでは自分のコミットとは関係のない他のコミットも自分がやったことになってしまっています。直し方が分からないので、このままpushしてしまうとおそらく皆さんのコミットも私がやったことになってしまいそうです。

行ったこと
https://qiita.com/muran001/items/dea2bbbaea1260098051
こちらの記事のやらかし２の「結構前のコミットを変更したい場合」を参考にして、it rebase -i <コミット>で対象のコミットをpick→editにして、
```
$ git commit --amend -m "コミットメッセージ" --author="user.name <user.email>"
$ git rebase --continue
```
を実行

その後に、`git log`をしても、対象のコミットのメールアドレスが空白のままだったので、同じQIITAのk爺の*(危険)歴史を完全に書き換える*と書かれている下記コマンドを実行しました。この時、このコマンドを実行して大丈夫だと判断した理由は、自分のブランチでは自分しかPUSHしておらず、他の人もfetchしたりしてないため問題ないと考えたからです。後から非常に反省しているのですが、この時点でやり方が分からないことを質問すれば良かったです。
```
git filter-branch -f --commit-filter '
    GIT_AUTHOR_NAME="SeijiNumata"
    GIT_AUTHOR_EMAIL="seizinumata@gmail.com"
    GIT_COMMITTER_NAME="SeijiNumata"
    GIT_COMMITTER_EMAIL="SeijiNumata@gmail.com"
    git commit-tree "$@"
' HEAD
```
その後、`git log`をしたところ、自分と関係のないコミット（？）のAuthorまで私に書き変わってしまっていました。
以下長いですがgit logの全文です。
```
numataseiji@numataseijinoMacBook-Pro ruby-practices % git log                            commit 0f13bb53d6aafe92be5399ec7577e6c137258efd (HEAD -> ls)
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Thu Nov 26 22:57:36 2020 +0900

    wcのファイルをコミットに入れないようにする

commit 0f13bb53d6aafe92be5399ec7577e6c137258efd (HEAD -> ls)
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Thu Nov 26 22:57:36 2020 +0900

    wcのファイルをコミットに入れないようにする

commit 81dd42902ee480cc8d791cb48be3f79ea4360495
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Wed Nov 25 18:26:16 2020 +0900

    commitのauthorのアイコンになっているかチェック

commit 33de5629428cb88a411179ed1abea94335213697
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Tue Nov 24 21:21:27 2020 +0900

    32行目を修正

commit db0aeafd1659afcc9c78073c776ce969edc45b79
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 22:22:58 2020 +0900

    ls提出

commit 0da6c3bf8c17f33fea3eda99f97bcacc266bc72a
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 21:48:54 2020 +0900

    clean 不要なファイルを削除
    
    if文の条件を=trueと書いてしまったところを削除しました

commit 47ecd65f87a07f09b4c301150ef1fe443a70c249
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 17:27:02 2020 +0900

    commit wccommand practice

commit 83d95ea25f4cdbb2ada57427c0bd15cfe3f539a9
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 17:26:00 2020 +0900

    wc

commit b1adecb0a9126f074b5b29e734382d2971865d8a
Author: user.name <user.email>
Date:   Mon Nov 23 17:10:19 2020 +0900

    コミットメッセージ

commit 26703037dfcf5503d310f4efe0d2cd363e1e254c
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 16:57:06 2020 +0900

    #first commit

commit e78f6b276e16eacf27f0c42fc1d046900d5b7307
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Tue Nov 17 09:32:01 2020 +0900

    rubocopを学ぶ順番を考慮し、適用すべきプラクティスについて言及する
    
    fizzbuzz、calendar、rakeのプラクティスではrubocopを使用しないため。

commit 61319e3e501dcc027b0109b33c37a9ae63b1e732
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 16 22:59:29 2020 +0900

    正解のソースコードを見ないよう注意してほしい旨を記載

commit 48a050b55e78a3c66633445d16d76dfe45826149
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 16 22:44:03 2020 +0900


Date:   Mon Nov 23 22:22:58 2020 +0900

    ls提出

commit 0da6c3bf8c17f33fea3eda99f97bcacc266bc72a
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 21:48:54 2020 +0900

    clean 不要なファイルを削除
    
    if文の条件を=trueと書いてしまったところを削除しました

commit 47ecd65f87a07f09b4c301150ef1fe443a70c249
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 17:27:02 2020 +0900

    commit wccommand practice

commit 83d95ea25f4cdbb2ada57427c0bd15cfe3f539a9
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 17:26:00 2020 +0900

    wc

commit b1adecb0a9126f074b5b29e734382d2971865d8a
Author: user.name <user.email>
Date:   Mon Nov 23 17:10:19 2020 +0900

    コミットメッセージ

commit 26703037dfcf5503d310f4efe0d2cd363e1e254c
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 16:57:06 2020 +0900

    #first commit

commit e78f6b276e16eacf27f0c42fc1d046900d5b7307
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Tue Nov 17 09:32:01 2020 +0900

    32行目を修正

commit db0aeafd1659afcc9c78073c776ce969edc45b79
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 22:22:58 2020 +0900

    ls提出

commit 0da6c3bf8c17f33fea3eda99f97bcacc266bc72a
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 21:48:54 2020 +0900

    clean 不要なファイルを削除
    
    if文の条件を=trueと書いてしまったところを削除しました

commit 47ecd65f87a07f09b4c301150ef1fe443a70c249
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 17:27:02 2020 +0900

    commit wccommand practice

commit 83d95ea25f4cdbb2ada57427c0bd15cfe3f539a9
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 17:26:00 2020 +0900

    wc

commit b1adecb0a9126f074b5b29e734382d2971865d8a
Author: user.name <user.email>
Date:   Mon Nov 23 17:10:19 2020 +0900

    コミットメッセージ

commit 26703037dfcf5503d310f4efe0d2cd363e1e254c
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 23 16:57:06 2020 +0900

    #first commit

commit e78f6b276e16eacf27f0c42fc1d046900d5b7307
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Tue Nov 17 09:32:01 2020 +0900

    rubocopを学ぶ順番を考慮し、適用すべきプラクティスについて言及する
    
    fizzbuzz、calendar、rakeのプラクティスではrubocopを使用しないため。

commit 61319e3e501dcc027b0109b33c37a9ae63b1e732
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 16 22:59:29 2020 +0900

    正解のソースコードを見ないよう注意してほしい旨を記載

commit 48a050b55e78a3c66633445d16d76dfe45826149
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 16 22:44:03 2020 +0900

    "フォルダ" の呼び方から "ディレクトリ" に統一

commit a3a52450d0978d94a594dd937639a9b288a46bc3
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Mon Nov 16 22:42:40 2020 +0900

    rubocopの実行をするように明記

commit c8507bc751db37334abb6a9790e26c407f7c316b
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Sun Nov 15 11:02:19 2020 +0900

    Write 'How to use'

commit 1fbdd8a30cf48d27d272a887de6ca0a6c204177a
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Sun Nov 15 10:45:44 2020 +0900

    Apply rubocop-fjord

commit 740037352d8d3518426e6a30df5f37bdb3e1ef4e
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Sun Nov 15 10:38:18 2020 +0900

    Add macOS & Windows gitignore settings

commit 129b9840fbd3fb59a3a6341609741b9642852532
Author: SeijiNumata <seizinumata@gmail.com>
Date:   Sun Nov 15 00:26:15 2020 +0900

    Create practice folders
```
このように、自分のコミットとは関係のないものまで修正されてしまいました。

大変申し訳ないのですが、ここからどうしたら良いでしょうか？
branchを削除して作り直したら、問題ありませんか？

また、今回の件に関してご迷惑をおかけしてしまい大変申し訳ありません。

2021-05-13 00:20 UTC, closed without merging