Fizzbuzz
fjordllc/ruby-practices pull request #67
Opened 2021-03-08 13:48 UTC by rosh-1228

ファイルを１つずつPRします

2021-03-09 05:38 UTC, komagata requested changes

2021-03-09 05:38 UTC, komagata commented on 01.fizzbuzz/fizzbuzz/fizzbuzz.rb
> +
不要な空行があるみたいです〜

2021-03-16 12:43 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-16 20:09 UTC, rosh-1228 commented
ありがとうございます！

2021-03-16 20:09 UTC, closed without merging